name: Deploy RunThru App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-backend:
    name: Deploy Backend to Google App Engine
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build backend
      run: npm run build:backend

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml \
          --project=runthru-backend-prod \
          --quiet \
          --set-env-vars="NODE_ENV=production,OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }},GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }},GCP_JSON_CREDENTIALS=${{ secrets.GCP_JSON_CREDENTIALS }},VIDEO_STORAGE_TYPE=gcp"

    - name: Verify deployment
      run: |
        echo "Backend deployed to: https://runthru-backend-prod.uc.r.appspot.com"
        curl -f https://runthru-backend-prod.uc.r.appspot.com/api/storage/info

  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build:frontend
      env:
        VITE_API_BASE_URL: https://runthru-backend-prod.uc.r.appspot.com
        VITE_WS_BASE_URL: wss://runthru-backend-prod.uc.r.appspot.com

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        vercel-args: '--prod --build-env VITE_API_BASE_URL=https://runthru-backend-prod.uc.r.appspot.com --build-env VITE_WS_BASE_URL=wss://runthru-backend-prod.uc.r.appspot.com'

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Test Backend Health
      run: |
        echo "Testing backend health..."
        curl -f https://runthru-backend-prod.uc.r.appspot.com/api/storage/info
        echo "✅ Backend is healthy"

    - name: Test Frontend Deployment
      run: |
        echo "✅ Frontend deployed successfully"
        echo "📝 Manual testing required for full integration" 