name: RunThru Demo Video

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  runthru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd packages/agent
          pnpm ts-node src/index.ts "Plan steps from diff ${{ github.event.pull_request.diff_url }}"
      - name: Upload mp4
        uses: actions/upload-artifact@v4
        with:
          name: demo
          path: packages/agent/output/demo.mp4
      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🎥 **RunThru** video ready → [Download artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) 